apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: minecraft
  name: minecraft
spec:
  ports:
  - name: minecraft-port
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: rcon-port
    port: 25575
    protocol: TCP
    targetPort: 25575
  selector:
    app: minecraft
  type: LoadBalancer
