apiVersion: v1
kind: ReplicationController
metadata:
  name: minecraft
  # The labels will be applied automatically
  # from the labels in the pod template, if not set
  # labels:
    # app: cassandra
spec:
  replicas: 2
  # The selector will be applied automatically
  # from the labels in the pod template, if not set.
  # selector:
      # app: cassandra
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:        
      - name: minecraft
      env:
        - name: EULA
          value: true
      image: openhack/minecraft-server:1.0
      ports:
        - containerPort: 25565
          name: intra-node
        - containerPort: 25575
          name: tls-intra-node
