apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: minecraft
  name: minecraft
spec:
  ports:
  - name: minecraft-port
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: rcon-port
    port: 25575
    protocol: TCP
    targetPort: 25575
  selector:
    app: minecraft
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: minecraft
  # The labels will be applied automatically
  # from the labels in the pod template, if not set
spec:
  replicas: 1
  # The selector will be applied automatically
  # from the labels in the pod template, if not set.
  selector:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:2.0
        ports:
          - containerPort: 25565
            name: minecraft-port
          - containerPort: 25575
            name: rcon-port
        volumeMounts:
          - mountPath: /data
            name: minecraft-data
        env:
          - name: EULA
            value: "true"
      volumes:
      - name: minecraft-data
        azureFile:
          secretName: azure-secret
          shareName: minecraft-share
          readOnly: false