---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{.Release.Name }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: minecraft-share
    readOnly: false
  claimRef:
    namespace: default
    name: az-{{.Release.Name }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: az-{{.Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
