apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: minecraft-{{.Release.Name }}
  name: minecraft-{{.Release.Name }}
spec:
  ports:
  - name: minecraft-port
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: rcon-port
    port: 25575
    protocol: TCP
    targetPort: 25575
  selector:
    app: minecraft-{{.Release.Name }}
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minecraft-statefulset-{{.Release.Name }}
  # The labels will be applied automatically
  # from the labels in the pod template, if not set
spec:
  serviceName: minecraft-service-{{.Release.Name }}
  replicas: 2
  # The selector will be applied automatically
  # from the labels in the pod template, if not set.
  selector:
    matchLabels:
      app: minecraft-{{.Release.Name }}
  template:
    metadata:
      labels:
        app: minecraft-{{.Release.Name }}
    spec:
      containers:
      - name: minecraft-{{.Release.Name }}
        image: openhack/minecraft-server:2.0
        ports:
          - containerPort: 25565
            name: minecraft-port
          - containerPort: 25575
            name: rcon-port
        volumeMounts:
          - mountPath: /data
            name: minecraft-data
        env:
          - name: EULA
            value: "true"
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: az-files-02
